### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by zaferatli** [Tomcat-42/aoc.zig-template#1]
Hey! first of all, thanks you repo.

when i try to run 

`zig build --build-runner build_runner.zig -Dyear=2023 -Dday=1 --watch run` command

i got these errors
```
build_runner.zig:14:26: error: root struct of file 'process' has no member named 'fatal'
const fatal = std.process.fatal;
              ~~~~~~~~~~~^~~~~~
/usr/local/Cellar/zig/0.13.0/lib/zig/std/process.zig:1:1: note: struct declared here
const std = @import("std.zig");
```

my zig env:

```
 "version": "0.13.0",
 "target": "x86_64-macos.14.0...14.0-none",
```

is it related my zig env or not? i'm not sure

**Comment by Tomcat-42** [comment]
> is it related my zig env or not? i'm not sure

Yes, I had to use a *custom* [build_runner.zig](https://github.com/ziglang/zig/blob/master/lib/compiler/build_runner.zig) (the one from the Zig master branch) to enable TLS support in the binary generated by the build system. By default, TLS is disabled to produce a leaner binary, but that means no HTTPS support.

In my opinion, the best approach is to update your Zig toolchain to the master version (0.14 at the time of this writing). I’m not sure how straightforward this is on macOS, as I couldn’t find a `zig-dev` package or similar in Homebrew, but you can [download it directly](https://ziglang.org/learn/getting-started/#direct).

I’m not sure if it’s feasible to implement this build system in older Zig versions, and I would advise against trying.

Let me know how you will proceed and if I can help you

**Comment by zaferatli** [comment]
yes after updated i got warned to upgrade zig 0.14. i update and its works like a charm. thanks
