### ISSUE TITLE
2016-Day 2: Non numeric solution

### ISSUE THREAD

**Issue by JohnnyWulgaru** [Tomcat-42/aoc.zig-template#4]
With commit 01f6d1b62d7ca13378f7875a5b9c61d0551c098f you've changed the return time for the solutions to i64. There are some (probably rare) challenges that require letters in the solution.

One of those examples is Year 2016, day 2 for me.

Thanks for writing this nice Advent of Code  setup for Zig. 
I am super new to Zig and planning on using it for the upcoming event to learn Zig properly!

**Comment by Tomcat-42** [comment]
Hello @JohnnyWulgaru, Thanks for pointing this case. Initially I though in returning all solutions as strings in the template, but that would require an extra allocation (insignificant in a small program like this, but anyway).

#7 Add a specialization for printing a formatted string if part1 or part2 return type is one. After the template generation for the choosen day, you can change the return type to `[]const u8`, For example:

```zig
const std = @import("std");
const mem = std.mem;
const eql = std.mem.eql;

input: []const u8,
allocator: mem.Allocator,

pub fn part1(this: *const @This()) !?i64 {
    _ = this;
    return 42;
}

pub fn part2(this: *const @This()) !?[]const u8 {
    return try std.fmt.allocPrint(
        this.allocator,
        "Custom tailored solution formatting: {d}",
        .{42},
    );
}

test "return types" {
    const allocator = std.testing.allocator;
    const input = "";

    const problem: @This() = .{
        .input = input,
        .allocator = allocator,
    };

    const pt1actual = (try problem.part1()).?;
    try std.testing.expectEqual(42, pt1actual);

    const pt2actual = (try problem.part2()).?;
    defer allocator.free(pt2actual); // not actually needed in main, because of the arena allocator

    try std.testing.expect(
        eql(u8, "Custom tailored solution formatting: 42", pt2actual),
    );
}
```

Let me know if it solves your use case.

**Comment by Tomcat-42** [comment]
I will close this as completed, but feel free to reopen the issue if you have a better idea or wants something else.
